export const personal = {
  name: "Ilia Duda",
  role: "Quantitative Finance · AI Engineering",
  tagline: "Building at the intersection of financial markets and machine intelligence.",
  location: "Boston, MA",
  email: "duda.i@northeastern.edu",
  linkedin: "https://linkedin.com/in/ilia-duda",
  github: "https://github.com/dudailia",
  resume: "/resume.pdf",
  available: "Open to Co-op · July 2026",
}

export const stats = [
  { value: 4, suffix: "T+", label: "AUM at Target Employer", prefix: "$" },
  { value: 20, suffix: "+", label: "Instruments Tracked", prefix: "" },
  { value: 3, suffix: "", label: "Production Systems Live", prefix: "" },
  { value: 290, suffix: "K+", label: "Orders Analyzed", prefix: "" },
]

export const valueProps = [
  {
    icon: "TrendingUp",
    title: "Finance First",
    description: "Real institutional experience: daily OFZ market briefings at BCS Bank, DCF and equity research models, macro analysis. Not just code — actual finance thinking.",
  },
  {
    icon: "Cpu",
    title: "Ships Real Products",
    description: "Sole engineer on a live options trading infrastructure and a production AI SaaS platform. Not demos. Production systems handling real money and real clients.",
  },
  {
    icon: "Award",
    title: "Proven at Every Level",
    description: "UK National Company of the Year. Perfect 65/65 on quant finance research. 300+ hours of Python and SQL. State Street co-op incoming at $4.4T AUM.",
  },
]

export const experience = [
  {
    slug: "state-street",
    company: "State Street Global Advisors",
    shortName: "State Street",
    role: "Investment Management Co-op",
    sub: "Supporting the Chief Investment Strategist",
    location: "Boston, MA",
    period: "Jul 2026 – Dec 2026",
    incoming: true,
    current: false,
    type: "finance",
    typeLabel: "Asset Management",
    accentColor: "#2563EB",
    summary: "Incoming co-op at one of the world's largest asset managers ($4.4T AUM), supporting the Chief Investment Strategist.",
    bullets: [
      "Joining State Street Global Advisors as Investment Management Co-op, supporting the Chief Investment Strategist team across macro research, investment communications, and market analysis.",
      "State Street Global Advisors manages over $4.4 trillion in assets under management, making it one of the largest investment managers in the world.",
    ],
    metrics: [
      { value: "$4.4T", label: "AUM" },
      { value: "Jul 2026", label: "Start Date" },
      { value: "Boston", label: "Location" },
    ],
    tags: ["Investment Management", "Macro Research", "CIS Team", "Boston"],
    companyDescription: "State Street Global Advisors is the investment management arm of State Street Corporation and one of the world's largest asset managers, known for creating the world's first ETF (SPY) and managing over $4.4 trillion in assets.",
    techStack: null as Record<string, string[]> | null,
    liveUrl: null as string | null,
    featuredOnHome: false,
  },
  {
    slug: "glacier-capital",
    company: "Glacier Capital Systems",
    shortName: "Glacier Capital",
    role: "Quantitative Software Engineer",
    sub: "",
    location: "Remote",
    period: "Jan 2026 – Present",
    incoming: false,
    current: true,
    type: "quant",
    typeLabel: "Proprietary Trading",
    accentColor: "#0F172A",
    summary: "Sole engineer for a live options trading firm. Built the full Python research stack: scanner, volatility surface model, regime detector, real-time alert dashboard.",
    bullets: [
      "Sole engineer for a proprietary options trading firm; built the full Python research stack including market scanner, multi-factor scoring engine, options chain analyzer, volatility surface model, regime detector, news sentiment parser, and position sizer covering 20+ instruments with all strategy parameters externalized to YAML.",
      "Designed a two-component options strategy engine combining short-dated premium-collection trades (0–10 DTE, ~10% OTM) and longer-dated directional positions (20–90 DTE, delta 0.30–0.60); enforced hard risk gates on risk/reward ratio, probability of profit, spread cost ceiling, and pair-correlation.",
      "Replaced a brittle macOS cron + email pipeline with a real-time trade-alert dashboard (Next.js 15 on Vercel, Supabase Postgres + Auth + Realtime, Python worker on Fly.io) that rescans candidates every 5 minutes during market hours.",
    ],
    metrics: [
      { value: "20+", label: "Instruments" },
      { value: "5 min", label: "Rescan Cadence" },
      { value: "2026", label: "Production Live" },
    ],
    tags: ["Python", "Black-Scholes", "Volatility Surface", "Next.js 15", "Supabase Realtime", "Fly.io", "YAML"],
    companyDescription: "Glacier Capital Systems is a proprietary options trading firm focused on systematic, rules-based options strategies across equity options markets.",
    techStack: {
      "Research Layer": ["Python", "pandas", "NumPy", "YAML config"],
      "Strategy Engine": ["Black-Scholes", "Greeks", "Volatility Surface", "Regime Detection"],
      "Dashboard": ["Next.js 15", "Supabase Realtime", "Vercel", "Fly.io"],
    } as Record<string, string[]>,
    liveUrl: null as string | null,
    featuredOnHome: true,
  },
  {
    slug: "closebooks",
    company: "CloseBooks",
    shortName: "CloseBooks",
    role: "Founder & Full-Stack Engineer",
    sub: "",
    location: "Boston, MA",
    period: "2024 – Present",
    incoming: false,
    current: true,
    type: "startup",
    typeLabel: "AI SaaS — Founder",
    accentColor: "#16A34A",
    summary: "Founded and built an AI-powered bookkeeping automation platform for CPA firms. Multi-tenant SaaS on Next.js + Supabase with Stripe billing and LLM transaction categorization.",
    bullets: [
      "Founded and built an AI-powered month-end close automation platform for small CPA and bookkeeping firms; deployed a multi-tenant Next.js 14 / TypeScript / Supabase (PostgreSQL with Row Level Security) application on Vercel with Stripe-billed three-tier subscription pricing as sole engineer.",
      "Engineered an LLM-based transaction categorization pipeline using the Anthropic Claude API that auto-maps bank statement line items (CSV and PDF) to a client's chart of accounts, reducing manual reconciliation to flagged exceptions only.",
      "Conducted ICP-targeted outreach to Boston-area CPA firms, delivered live product demos, and currently in active partnership conversations with a practicing bookkeeping firm in Canton, MA.",
    ],
    metrics: [
      { value: "Multi-tenant", label: "Architecture" },
      { value: "3-tier", label: "Stripe Billing" },
      { value: "Canton MA", label: "Partner in Talks" },
    ],
    tags: ["Next.js 14", "TypeScript", "Supabase", "PostgreSQL", "Anthropic API", "Stripe", "Vercel"],
    companyDescription: "CloseBooks automates the month-end close process for small CPA and bookkeeping firms using LLM-based transaction categorization. Built from scratch as a sole founder and engineer.",
    techStack: {
      "Frontend": ["Next.js 14", "TypeScript", "React"],
      "Backend & DB": ["Supabase", "PostgreSQL", "Row Level Security"],
      "AI Layer": ["Anthropic Claude API", "LLM pipelines"],
      "Billing & Deploy": ["Stripe", "Vercel"],
    } as Record<string, string[]>,
    liveUrl: "https://closebooks-app.vercel.app" as string | null,
    featuredOnHome: true,
  },
  {
    slug: "bcs-bank",
    company: "BCS Bank — Investment Banking Division",
    shortName: "BCS Bank",
    role: "Investment Banking Analyst Intern",
    sub: "",
    location: "Moscow, Russia",
    period: "Jul – Aug 2023",
    incoming: false,
    current: false,
    type: "finance",
    typeLabel: "Investment Banking",
    accentColor: "#7C3AED",
    summary: "Covered Russian energy, metals, and banking sectors. Built DCF and comp models for equity research. Wrote daily market briefings on OFZ bonds, MOEX, and Bank of Russia policy.",
    bullets: [
      "Covered Russian energy (Lukoil, Novatek, Tatneft), metals (Severstal, Mechel), and banking sectors during a period of strong MOEX performance; built DCF, comparable company, and sensitivity models supporting client-facing equity research.",
      "Wrote daily market briefings on OFZ government bond movements, oil and gas equity flows, and MOEX index activity, summarizing Bank of Russia policy actions and translating macro signals into desk-relevant takeaways.",
      "Conducted comprehensive sector analysis across 6 companies using DCF valuation and comparable company analysis.",
      "Gained hands-on exposure to investment banking workflows including financial statement analysis, valuation methodologies (DCF, trading comps, precedent transactions), and capital markets operations.",
    ],
    metrics: [
      { value: "6", label: "Companies Covered" },
      { value: "Daily", label: "Market Briefings" },
      { value: "DCF", label: "Modeling" },
    ],
    tags: ["DCF Modeling", "Equity Research", "OFZ Bonds", "MOEX", "Macro Analysis", "Comparable Company"],
    companyDescription: "BCS Bank is one of Russia's largest investment banks, providing full-service investment banking, equity research, and capital markets services.",
    techStack: null as Record<string, string[]> | null,
    liveUrl: null as string | null,
    featuredOnHome: true,
  },
  {
    slug: "monito",
    company: "Monito — Young Enterprise UK",
    shortName: "Monito",
    role: "Co-Founder & Financial Director",
    sub: "",
    location: "Bromsgrove, UK",
    period: "Sep 2022 – Sep 2023",
    incoming: false,
    current: false,
    type: "startup",
    typeLabel: "Entrepreneurship",
    accentColor: "#D97706",
    summary: "Co-founded a student venture that won UK National Company of the Year and advanced to the European Finals — the top outcome in Young Enterprise UK.",
    bullets: [
      "Co-founded a Young Enterprise student venture that won UK National Company of the Year and advanced to the European Finals — the top program-wide outcome in Young Enterprise UK.",
      "Won Company of the Year at regional level (Worcestershire & Warwickshire), then West Midlands level, then UK National — a full sweep of the competition.",
      "Led the finance function: budgeting, pricing strategy, P&L tracking, investor pitch materials; coordinated a five-person team through national rounds.",
    ],
    metrics: [
      { value: "🏆", label: "UK National Winner" },
      { value: "🌍", label: "European Finalist" },
      { value: "5", label: "Team Members Led" },
    ],
    tags: ["Entrepreneurship", "Financial Modeling", "UK National Winner", "European Finalist", "Young Enterprise"],
    companyDescription: "Young Enterprise UK is the UK's leading enterprise education charity. Monito competed nationally against thousands of teams and won the top prize.",
    techStack: null as Record<string, string[]> | null,
    liveUrl: null as string | null,
    featuredOnHome: false,
  },
]

export const projects = [
  {
    slug: "glacier-trading-engine",
    title: "Options Trading Infrastructure",
    subtitle: "Glacier Capital Systems",
    type: "Quantitative Finance",
    status: "Live in Production",
    statusColor: "green" as const,
    featured: true,
    summary: "Full Python research stack for a live options trading firm. 20+ instruments, real-time alerts, volatility surface modeling.",
    description: "Built from scratch as sole engineer: a complete quantitative research and trade-alert system for a proprietary options trading firm. Covers 20+ equity options instruments with 5-minute rescan cadence during market hours.",
    whatIBuilt: [
      {
        title: "Market Scanner & Scoring Engine",
        body: "Multi-factor scoring system that screens the full options universe against configurable criteria: volume, open interest, implied volatility rank, bid-ask spread, and custom factor weights. All parameters live in YAML files.",
      },
      {
        title: "Options Chain Analyzer",
        body: "Parses full options chains, calculates Greeks (delta, gamma, theta, vega), identifies optimal strike/expiry combinations for two strategy types: short premium (0–10 DTE) and directional (20–90 DTE, delta 0.30–0.60).",
      },
      {
        title: "Volatility Surface Model",
        body: "Builds implied volatility surfaces across strikes and expirations. Used for identifying rich/cheap options and detecting term structure anomalies.",
      },
      {
        title: "Real-Time Alert Dashboard",
        body: "Next.js 15 + Supabase Realtime dashboard replacing a brittle cron+email system. Python worker on Fly.io rescans every 5 minutes during market hours, pushes diff-based alerts.",
      },
    ],
    metrics: [
      { value: "20+", label: "Instruments Covered" },
      { value: "5 min", label: "Rescan Cadence" },
      { value: "100%", label: "Solo Built" },
    ],
    tech: {
      "Research": ["Python", "pandas", "NumPy", "YAML"],
      "Options Math": ["Black-Scholes", "Greeks", "Volatility Surface"],
      "Dashboard": ["Next.js 15", "Supabase Realtime", "Fly.io", "Vercel"],
    },
    links: { github: null as string | null, live: null as string | null },
    accentColor: "#0F172A",
  },
  {
    slug: "closebooks-saas",
    title: "CloseBooks — AI Bookkeeping Platform",
    subtitle: "Founder Project",
    type: "AI / Full-Stack SaaS",
    status: "Active — Seeking Partners",
    statusColor: "blue" as const,
    featured: true,
    summary: "Multi-tenant SaaS platform automating month-end close for CPA firms. LLM pipeline + Stripe billing + Row Level Security.",
    description: "Founded and built solo: a production AI SaaS platform that automates the most tedious part of accounting — month-end close. CPA firms upload bank statements, the LLM pipeline categorizes every transaction, and accountants only review flagged exceptions.",
    whatIBuilt: [
      {
        title: "Multi-Tenant Architecture",
        body: "Next.js 14 App Router with Supabase PostgreSQL. Full Row Level Security ensures tenant data isolation at the database level.",
      },
      {
        title: "LLM Transaction Categorization",
        body: "Pipeline built on the Anthropic Claude API. Accepts bank statement uploads (CSV and PDF), extracts line items, and maps each to the client's chart of accounts.",
      },
      {
        title: "Three-Tier Stripe Billing",
        body: "Complete subscription billing with Stripe: free trial, professional, and enterprise tiers. Stripe webhooks update Supabase subscription state.",
      },
      {
        title: "Go-to-Market",
        body: "Conducted ICP-targeted outreach to Boston-area CPA firms. Delivered live product demos. Currently in active partnership conversations.",
      },
    ],
    metrics: [
      { value: "Multi-tenant", label: "Architecture" },
      { value: "LLM", label: "Categorization" },
      { value: "Stripe", label: "Billing" },
    ],
    tech: {
      "Frontend": ["Next.js 14", "TypeScript", "React"],
      "Backend": ["Supabase", "PostgreSQL", "Row Level Security"],
      "AI": ["Anthropic Claude API", "LLM pipelines"],
      "Infra": ["Stripe", "Vercel"],
    },
    links: { github: null as string | null, live: "https://closebooks-app.vercel.app" as string | null },
    accentColor: "#16A34A",
  },
  {
    slug: "yandex-analytics",
    title: "Yandex Afisha: Full-Cycle Analytics",
    subtitle: "Yandex Practicum Capstone",
    type: "Data Analytics",
    status: "Completed",
    statusColor: "green" as const,
    featured: true,
    summary: "End-to-end analytics pipeline for Russia's leading event ticketing platform. 290K+ orders, PostgreSQL, DataLens dashboard, Python EDA.",
    description: "Capstone project for the Yandex Practicum Data Analytics program. Built a complete analytical workflow from SQL ingestion through Python EDA to an interactive business dashboard for Yandex Afisha's product team.",
    whatIBuilt: [
      {
        title: "PostgreSQL Data Pipeline",
        body: "Connected to a PostgreSQL database with 290,000+ orders across five relational tables. Ran SQL queries for data quality auditing, duplicate detection, multi-currency handling (RUB/KZT), and outlier flagging.",
      },
      {
        title: "Interactive DataLens Dashboard",
        body: "Designed an interactive business dashboard in Yandex DataLens with KPI indicators, time-series charts, device and event-type breakdowns, and filterable tables by region and category.",
      },
      {
        title: "Python Exploratory Analysis",
        body: "Full EDA in Python (pandas, seaborn, scipy): currency conversion, outlier filtering at the 99th percentile, seasonality decomposition, and statistical hypothesis testing.",
      },
      {
        title: "Key Findings",
        body: "Mobile users drive ~79% of revenue. Concerts and theatre lead by both volume and ticket value. Order peaks align with the start of the autumn cultural season.",
      },
    ],
    metrics: [
      { value: "290K+", label: "Orders Analyzed" },
      { value: "79%", label: "Revenue from Mobile" },
      { value: "5", label: "Relational Tables" },
    ],
    tech: {
      "Data": ["PostgreSQL", "SQL"],
      "Analysis": ["Python", "pandas", "seaborn", "scipy"],
      "Visualization": ["Yandex DataLens"],
    },
    links: { github: "https://github.com/dudailia" as string | null, live: null as string | null },
    accentColor: "#DC2626",
  },
  {
    slug: "quant-finance-research",
    title: "Quantitative Finance Research",
    subtitle: "FINA 4335 — Northeastern University",
    type: "Academic Research",
    status: "65/65 — Perfect Score",
    statusColor: "green" as const,
    featured: false,
    summary: "Fama-French regressions, Black-Scholes engine, CAPM backtesting, Sharpe ratio annualization. Perfect score on 33 S&P 1500 stocks.",
    description: "Full academic quantitative finance project for FINA 4335. Covers Fama-French factor regressions, Black-Scholes options pricing, CAPM backtesting, and portfolio construction with rigorous controls for look-ahead bias.",
    whatIBuilt: [
      {
        title: "Fama-French 3-Factor Regression",
        body: "Estimated alpha and beta exposures to market, size (SMB), and value (HML) factors for 33 S&P 1500 stocks over 25 years (Jan 2000–Dec 2025).",
      },
      {
        title: "Black-Scholes Options Pricing Engine",
        body: "Implemented full Black-Scholes formula in Python with correct d1/d2 calculation, cumulative normal distribution, and put-call parity verification.",
      },
      {
        title: "CAPM Backtesting & Portfolio Construction",
        body: "Buy-and-hold portfolio construction with vectorized methods. Sharpe ratio annualized correctly (×√12). Maximum drawdown computed on rolling cumulative returns.",
      },
    ],
    metrics: [
      { value: "65/65", label: "Perfect Score" },
      { value: "33", label: "Stocks Analyzed" },
      { value: "25yr", label: "Data Range" },
    ],
    tech: {
      "Analysis": ["Python", "pandas", "NumPy", "statsmodels"],
      "Data": ["yfinance", "Fama-French factors"],
      "Visualization": ["matplotlib", "seaborn", "Jupyter"],
    },
    links: { github: "https://github.com/dudailia" as string | null, live: null as string | null },
    accentColor: "#7C3AED",
  },
  {
    slug: "performance-analytics",
    title: "Long/Short Performance Analytics",
    subtitle: "Glacier Capital Systems",
    type: "Financial Analytics",
    status: "+5.3% Alpha Delivered",
    statusColor: "green" as const,
    featured: false,
    summary: "7-sheet analytics package for a SMCI long + 5 short positions portfolio. +23.3% total return vs +18.0% S&P 500.",
    description: "Comprehensive analytical package for a long/short equity model at Glacier Capital. SMCI as the long position against 5 short positions. Full attribution analysis, drawdown charts, and scenario modeling.",
    whatIBuilt: [
      {
        title: "Performance Attribution",
        body: "Broke down total return (+23.3% vs S&P +18.0%) into long contribution, short contribution, and net alpha (+5.3%) at position level.",
      },
      {
        title: "Drawdown & Risk Analysis",
        body: "Rolling maximum drawdown, peak-to-trough periods, recovery analysis. Risk metrics: Sharpe ratio, Sortino ratio, beta-adjusted returns.",
      },
      {
        title: "Scenario Modeling",
        body: "Stress tests across market regimes. Bull/base/bear scenarios for each position. Correlation matrix for the 6-stock portfolio.",
      },
    ],
    metrics: [
      { value: "+23.3%", label: "Total Return" },
      { value: "+5.3%", label: "Alpha vs S&P" },
      { value: "7", label: "Chart Deliverables" },
    ],
    tech: {
      "Analysis": ["Python", "pandas", "NumPy"],
      "Visualization": ["matplotlib", "openpyxl"],
      "Delivery": ["Excel", "7-sheet workbook"],
    },
    links: { github: null as string | null, live: null as string | null },
    accentColor: "#0F172A",
  },
]

export const education = {
  university: {
    name: "Northeastern University",
    college: "College of Science",
    degree: "B.S. Mathematics and Business Administration",
    period: "Sep 2024 – May 2028",
    location: "Boston, MA",
    courses: [
      "Probability & Statistical Theory",
      "Partial Differential Equations",
      "Stochastic Processes (Markov Chains, Queueing Theory)",
      "Mathematical Statistics (Hypothesis Testing, Chi-Square)",
      "Linear Algebra",
      "Investments",
      "Corporate Finance",
      "Blockchain Applications in Finance",
    ],
  },
  schools: [
    {
      name: "Bromsgrove School",
      qualification: "A-Levels",
      period: "2022 – 2024",
      location: "Bromsgrove, UK",
    },
    {
      name: "The King's School, Canterbury",
      qualification: "GCSE / Secondary",
      period: "2021 – 2022",
      location: "Canterbury, UK",
    },
  ],
  certifications: [
    {
      name: "Claude Code in Action",
      issuer: "Anthropic",
      monogram: "A",
      monogramColor: "#000000",
      year: "Apr 2026",
      expires: "May 2036",
      skills: ["Agentic AI Development", "Claude Code Subagents", "MCP Servers"],
    },
    {
      name: "AI Engineer for Data Scientists Associate",
      issuer: "DataCamp",
      monogram: "DC",
      monogramColor: "#03EF62",
      year: "Feb 2026",
      expires: "Feb 2030",
      skills: ["Python", "PyTorch", "Machine Learning"],
    },
    {
      name: "Generative AI in Action",
      issuer: "IBM",
      monogram: "IBM",
      monogramColor: "#0F62FE",
      year: "2026",
      expires: null,
      skills: ["Generative AI", "LLMs"],
    },
    {
      name: "BCG Teaming Simulation",
      issuer: "Boston Consulting Group",
      monogram: "BCG",
      monogramColor: "#00A651",
      year: "2025",
      expires: null,
      skills: ["Strategy", "Consulting"],
    },
  ],
}

export const skillGroups = [
  {
    label: "Programming",
    skills: ["Python", "TypeScript", "JavaScript", "SQL", "pandas", "NumPy", "SciPy", "scikit-learn", "PyTorch", "matplotlib", "seaborn"],
  },
  {
    label: "Quantitative Finance",
    skills: ["Options Pricing", "Black-Scholes", "Greeks", "Volatility Surface", "Portfolio Construction", "Fama-French Regression", "CAPM", "DCF Modeling", "Equity Research", "OFZ Bonds", "Macro Analysis", "Sharpe Ratio", "Max Drawdown"],
  },
  {
    label: "AI & Machine Learning",
    skills: ["LLM Pipelines", "Anthropic Claude API", "Agentic AI", "NLP", "Generative AI", "Statistical Hypothesis Testing", "Regression Analysis"],
  },
  {
    label: "Web & Infrastructure",
    skills: ["Next.js 15", "React", "Supabase", "PostgreSQL", "Row Level Security", "Vercel", "Fly.io", "Git", "Stripe", "Jupyter"],
  },
  {
    label: "Data Analytics",
    skills: ["Yandex DataLens", "Dashboard Design", "EDA", "Seasonality Analysis", "Outlier Detection", "A/B Testing"],
  },
]
